export default function(){
    const maindiv=document.createElement('div');
    maindiv.classList.add('contact');
    const div1=document.createElement('div');
    const heading=document.createElement('h1');
    heading.textContent="Contact Us";
    const p1=document.createElement('p');
    p1.textContent="We’d love to hear from you! Whether you have questions, feedback, or special requests, feel free to reach out. Our team is here to help!";
    const div2=document.createElement('div');
    const location=document.createElement('h2');
    location.textContent="Location";
    const address=document.createElement('div');
    const line1=document.createElement('p');
    line1.textContent="The Urban Kitchen";
    const line2=document.createElement('p');
    line2.textContent="1234 Culinary Lane"
    const line3=document.createElement('p');
    line3.textContent="Koramangala, Bangalore -560034"
    const line4=document.createElement('p');
    line4.textContent="India";
    address.append(line1,line2,line3,line4);
    div2.append(location,address);
    const div3=document.createElement('div');
    const phone=document.createElement('h2');
    phone.textContent="Phone";
    const number=document.createElement('p');
    number.textContent="📞 +91 98765 43210";
    div3.appendChild(phone);
    div3.appendChild(number);
    const div4=document.createElement('div');
    const email=document.createElement('h2');
    email.textContent='Email';
    const emailid=document.createElement('p');
    emailid.textContent="✉️ contact@theurbankitchen.in";
    div4.appendChild(email);
    div4.appendChild(emailid);
    const div5=document.createElement('div');
    const openingtime=document.createElement('h2');
    openingtime.textContent="Opening Hours";
    const hours=document.createElement('div');
    const hours1=document.createElement('p');
    hours1.textContent="Monday to Friday: 11:00 AM – 10:00 PM";
    const hours2=document.createElement('p');
    hours2.textContent="Saturday: 12:00 PM – 11:00 PM";
    const hours3=document.createElement('p');
    hours3.textContent="Sunday: 12:00 PM – 9:00 PM";
    hours.append(hours1,hours2,hours3);
    div5.append(openingtime,hours);
    const div6=document.createElement('div');
    const follow=document.createElement('h2');
    follow.textContent="Follow Us";
    const desc=document.createElement('p');
    desc.textContent="Stay connected through our social media for updates, special offers, and more!";
    const links=document.createElement('div');
    const link1=document.createElement('p');
    link1.textContent="Facebook: facebook.com/theurbankitchenBLR";
    const link2=document.createElement('p');
    link2.textContent="Instagram: instagram.com/theurbankitchen";
    const link3=document.createElement('p');
    link3.textContent="Twitter: twitter.com/urbankitchenBLR";
    links.append(link1,link2,link3);
    div6.append(follow,desc,links);
    maindiv.append(heading,div1,div2,div3,div4,div5,div6);
    return maindiv;
}